# Generated by Django 2.2.4 on 2019-09-22 07:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ahlak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslıkpost', models.CharField(max_length=20)),
                ('icerikpost', ckeditor.fields.RichTextField()),
                ('imageflied', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='felsefe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslıkpost', models.CharField(max_length=20)),
                ('icerikpost', ckeditor.fields.RichTextField()),
                ('imageflied', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='mantık',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslıkpost', models.CharField(max_length=20)),
                ('icerikpost', ckeditor.fields.RichTextField()),
                ('imageflied', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='matematik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslıkpost', models.CharField(max_length=20)),
                ('icerikpost', ckeditor.fields.RichTextField()),
                ('imageflied', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='yazılım',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslıkpost', models.CharField(max_length=20)),
                ('icerikpost', ckeditor.fields.RichTextField()),
                ('imageflied', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='nesne1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ısım', models.CharField(max_length=15)),
                ('ısım2', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('nesne', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='calısannesne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ısım', models.CharField(max_length=15)),
                ('ısım2', models.TextField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('nesne', django.db.models.manager.Manager()),
            ],
        ),
    ]
