# Generated by Django 2.2.4 on 2019-10-21 05:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslıkpost', models.CharField(max_length=100)),
                ('içerikpost', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ahlak',
            name='imageflied',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='felsefe',
            name='imageflied',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mantık',
            name='imageflied',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='matematik',
            name='imageflied',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='yazılım',
            name='imageflied',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
