# Generated by Django 2.2.4 on 2019-10-21 05:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oz', '0002_auto_20191021_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='anad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslıkpost', models.CharField(max_length=100)),
                ('içerikpost', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
